import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import LIST_OF_PROJECT_DOCS from './constants';

const sidebars: SidebarsConfig = {}
for (const project of LIST_OF_PROJECT_DOCS) {
    sidebars[project.sidebarID] = [{
        type: 'autogenerated',
        dirName: project.dirName
    }]
}

export default sidebars;